catalogue/urls.py
from django.conf.urls import *
#from catalogue.views import get_ordering_status

urlpatterns = patterns('',
#    (r'^orders/$', 'ordercoops.catalogue.admin_views.list_orders'),
    (r'^orders/new/$', 'ordercoops.catalogue.admin_views.edit_order'),
    (r'^orders/edit/(?P<order_id>[\d]+)/$', 'ordercoops.catalogue.admin_views.edit_order'),
    (r'^upload/$', 'ordercoops.catalogue.admin_views.upload_catalogue'),
    (r'^upload-done/$', 'ordercoops.catalogue.admin_views.upload_catalogue_done'),
)
 

urls.py
from django.conf.urls import *
from django.contrib import admin
admin.autodiscover()
from django.conf import settings

urlpatterns = patterns('',
    url(r'^order-(?P<order_id>\d+)/', include('catalogue.ordering_urls')),
    url(r'^coop-admin/', include('catalogue.coop_admin_urls')),

    url(r'^catalogue/', include('ordercoops.catalogue.urls')),
    url(r'^$', 'ordercoops.views.homepage'),
    url(r'^user/', include('ordercoops.userprofile.urls')),
    url(r'^r/', include('django.conf.urls.shortcut')), # For the 'View on site' button in the admin

#    (r'^admin/user-passwords/$', 'ordercoops.views.user_passwords'),
#    (r'^admin/user-emails/$', 'ordercoops.views.user_emails'),

    url('^admin/', admin.site.urls),
    url(r'^robots.txt$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'path':'robots.txt'}),
)
 

catalogue/models.py
# -*- coding: utf-8 -*-
import os, re, csv
import math
from decimal import *
from datetime import datetime, date
from django.db import models, transaction
from django.template.defaultfilters import slugify
from userprofile.models import UserProfile, Cooperative
from ordercoops import settings
VAT_CHOICES = (('V', 'V'), ('5', '5'))
NEW_CHOICES = (('NEW', 'NEW'),)
PRICECHANGE_CHOICES = (('UP', 'UP'), ('DOWN', 'DOWN'))
ONOFFER_CHOICES = (('OFFER', 'OFFER'), ('END', 'END'))
from ordercoops.catalogue.splittable_items import SPLITTABLE_ITEMS

class EssentialProductManager(models.Manager):
    def import_from_textfile(self, filepath, catalogue):
        self.model.objects.filter(catalogue=catalogue).delete()
        csvfile = open(filepath)
        dictreader = csv.DictReader(csvfile, dialect='excel')
        multispace_re = re.compile(' +')
        for row in dictreader:
            row = dict([(k, multispace_re.sub(' ', row[k].strip())) for k in row.keys()])
            if not row['Code']:
                continue
            try:
                c=ProductCategory.objects.get(name=row['Catname'], catalogue=catalogue)
            except ProductCategory.DoesNotExist:
                c = ProductCategory.objects.create(name=row['Catname'], slug=slugify(row['Catname']), catalogue=catalogue)
                c.save()

            if row['Price']:
                net_price=float(row['Price'])
            else:
                net_price=0

            if row['VAT'] == 'V':
                vat_rate = 0.15
            elif row['VAT'] == 'F':
                vat_rate = 0.5
            elif row['VAT'] == 'Z':
                vat_rate = 0
            else:
                raise ValueError("Bad VAT value (%s)" % row['VAT'])

            p = self.model.objects.create(
                catalogue=catalogue,
                supplier_product_code=row['Code'],
                brand_name=row['Origin'],
                brand_slug=slugify(row['Origin']),
                category=c,
                name=row['Description'],
                size=row['Pack_Size'],
                net_price=net_price,
                gross_price=net_price*(1+vat_rate),
                vat_rate=vat_rate,
                organic = row['Org']=='ORG' and True or False,
                fair_trade = row['FT']=='F' and True or False,
                gluten_free = row['GF']=='G' and True or False,
            )
            p.save()
        csvfile.close()
        catalogue.data_import_completed=True
        catalogue.save()

# Suma like to vary the column names in the csv file. This maps names to
# canonical header names:
HEADER_EQUIVS = (
("PLCDE", "PL CODE"),
("PLTEXT", "PL TEXT"),
("FGOSV", "BFGOSV"),
("PLDESC", "DESCRIPTION"),
("NEW CATEGORY", "CATEGORY"),
("ON OFFER?", "ON OFFER"),
)

class SumaProductManager(models.Manager):
    @transaction.commit_on_success
    def import_from_textfile(self, filepath, catalogue):
        SumaProduct.objects.filter(catalogue=catalogue).delete()
        csvfile = open(filepath, 'U')
        headers = [z.strip() for z in csvfile.readline().strip().split('\t')]
        for e, c in HEADER_EQUIVS:
            if e in headers:
                headers[headers.index(e)] = c
        dictreader = csv.DictReader(csvfile, headers, dialect='excel-tab')
        for row in dictreader:
            row = dict([(k, v.strip() if isinstance(v, basestring) else v) for k, v in row.iteritems()])
            if not row['PL CODE']:
                continue
            try:
                c=ProductCategory.objects.get(name=row['CATEGORY'], catalogue=catalogue)
            except ProductCategory.DoesNotExist:
                c = ProductCategory.objects.create(name=row['CATEGORY'], slug=slugify(row['CATEGORY']), catalogue=catalogue)
                c.save()
#            brand=row['BRAND'].
#            try:
#                b = Brand.objects.get(name=brand)
#            except Brand.DoesNotExist:
#                if re.search('\w', brand):
#                    b = Brand.objects.create(name=brand, slug=slugify(brand))
#                    b.save()
#                else:
#                    b=None
            if row['PRICE']=='Discontinued':
                discontinued=True
            else:
                discontinued=False

            if row['PRICE']=='FREE':
                net_price=Decimal(0)
            elif row['PRICE']:
                net_price=Decimal(row['PRICE'])
            else:
                net_price=None

            if row['VAT'] in ('', None):
                vat_rate = Decimal('0')
            elif row['VAT'].lower() == 'v':
                vat_rate = Decimal('0.20')
            else:
                vat_rate = Decimal(row['VAT'])/100
                # If you get an exception here, there's something unexpected
                # in the VAT column.
                 
            p = SumaProduct.objects.create(
                catalogue=catalogue,
                supplier_product_code=row['PL CODE'],
                brand_name=row['BRAND'],
                brand_slug=slugify(row['BRAND']),
                category=c,
                name=row['DESCRIPTION'],
                pl_text=row['PL TEXT'].strip(' '),
                size=row['SIZE'],
                net_price=net_price,
                gross_price=None if net_price is None else net_price*(Decimal(1)+vat_rate),
                vat_rate=vat_rate,
                rrp=row['RRP'] or None,
                bfgosv=row['BFGOSV'],
                new=row['NEW?'] and True or False,
                on_offer=row['ON OFFER'] and True or False,
                normal_price=row['NORMAL PRICE'] or None,
                normal_rrp=row['NORMAL RRP'] or None,        
                discontinued=discontinued,
            )
            p.save()
        csvfile.close()
        catalogue.data_import_completed=True
        catalogue.save()
        for i in SPLITTABLE_ITEMS:
            try:
                p = BaseProduct.objects.get(catalogue=catalogue, supplier_product_code=i[0])
                p.outgoingUnitSize = i[1]
                p.outgoingUnitsPerIncomingUnit = i[2]
                p.save()
            except BaseProduct.DoesNotExist:
                pass
#                print "No such product: %s" % i[0]

class Catalogue(models.Model):
    ref = models.SlugField(unique=True, help_text="eg. Suma, May-June-2008")
    csvfile = models.FileField(upload_to='catalogues')
    start_date = models.DateField(blank=True, null=True)
    expiry_date = models.DateField(blank=True, null=True)
    data_import_completed = models.BooleanField(default=False)
    supplier = models.CharField(max_length=50, choices=(('Suma','Suma'), ('Essential','Essential')))

    def __unicode__(self):
        return "%s - %s" % (self.supplier, self.ref)
#    objects = CatalogueManager()

    def csvfilepath(self):
        return os.path.join(settings.MEDIA_ROOT, self.csvfile.name)

    @transaction.commit_on_success
    def save(self, *args, **kwargs):
        super(Catalogue, self).save(*args, **kwargs)
        # This is quite nasty
        if self.csvfile and not self.data_import_completed:
            globals()['%sProduct' % self.supplier].objects.import_from_textfile(self.csvfilepath(), self)


#class Brand(models.Model):
#    name = models.CharField(max_length=250, unique=True, db_index=True)
#    slug = models.SlugField()
#
#    class Meta:
#        ordering=['name',]
#
#    def __unicode__(self):
#        return self.name
#
class ProductCategory(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(db_index=True)
    catalogue = models.ForeignKey(Catalogue, db_index=True)

    class Meta:
        ordering=['slug',]
        unique_together = (("name", "catalogue"), ("slug", "catalogue"))

    def __unicode__(self):
        return self.name


class BaseProduct(models.Model):
    """ Base model with some likely common fields """
    catalogue = models.ForeignKey(Catalogue, db_index=True)
    supplier_product_code = models.CharField(max_length=100, db_index=True, blank=True)
    name = models.TextField()
    brand_name = models.CharField(max_length=50, db_index=True)
    brand_slug = models.CharField(max_length=50, db_index=True)
    category = models.ForeignKey(ProductCategory, db_index=True, blank=True, null=True)
    size = models.CharField(max_length=100, blank=True, null=True)
    net_price = models.DecimalField(decimal_places=2, max_digits=6, null=True, blank=True)
    vat_rate = models.DecimalField(decimal_places=4, max_digits=5, default=0)
    gross_price = models.DecimalField(decimal_places=2, max_digits=6, null=False, blank=False)
    # splittable items:
    outgoingUnitSize = models.CharField(max_length=100, null=True, blank=True)
    outgoingUnitsPerIncomingUnit = models.IntegerField(null=True, blank=True)


    def is_splittable(self):
        return self.outgoingUnitsPerIncomingUnit and self.outgoingUnitSize and True

    def get_price(self):
        if self.is_splittable():
            return math.ceil(100*float(self.gross_price) / self.outgoingUnitsPerIncomingUnit)/100
        else:
            return self.gross_price

    def extra_info(self):
        """ override this to show extra info in the catalogue browser """
        return ''

    def get_outgoing_unit_size(self):
        if self.is_splittable():
            return self.outgoingUnitSize
        else:
            return self.size

    class Meta:
#        ordering=['category', 'grossPrice']
        ordering=['supplier_product_code']
#        abstract=True

    def save(self, *args, **kwargs):
        self.gross_price = self.net_price * (Decimal(1)+self.vat_rate)
        super(BaseProduct, self).save(*args, **kwargs)

    def __unicode__(self):
        return "%s: %s (%s)" % (self.supplier_product_code, self.name, self.brand_name and self.brand_name or '')

class EssentialProduct(BaseProduct):
    country = models.CharField(max_length=25, null=True, blank=True)
    organic = models.BooleanField()

catalogue/templates/catalogue/admin/confirm_delete_order.html
{% extends "catalogue/base.html" %}

{% block content %}

<p>Are you sure you really want to delete this order?</p>

<p><a href="./?confirm=yes">Yes</a> | <a href="./?confirm=no">No</a></p>

{% endblock%}

catalogue/templates/catalogue/admin/coop-admin-home.html
{% extends "catalogue/base.html"%}

{% block content%}

<div style="background-color:#fff">
{% for message in messages %}
<p>{{message}}</p>
{% endfor %}
</div>

{% if object_list %}
<table>
<tr>
<th>Open?</th>
<th>Supplier</th>
<th>Delivery date</th>
<th>&nbsp;</th>
<th>&nbsp;</th>
<th>&nbsp;</th>
<th>&nbsp;</th>
</tr>
{% for order in object_list %}
<tr>
<td>{% if order.open %}Y{% else %}N{% endif %}</td>
<td>{{order.catalogue.supplier}}</td>
<td>{{order.delivery_date}}</td>
<td><a href="/coop-admin/edit-order/{{order.id}}/">Edit</a></td>
<td><a href="/coop-admin/delete-order/{{order.id}}/">Delete</a></td>
<td><a href="/coop-admin/uncollated-order/{{order.id}}/">View uncollated</a></td>
<td><a href="/coop-admin/collated-order/{{order.id}}/">View collated</a></td>
</tr>
{% endfor %}
</table>
{% else %}
<p>You have no orders scheduled.</p>
{% endif %}

<p><a href="/coop-admin/new-order/">Schedule a new order</a></p>

{% endblock %}

catalogue/templates/catalogue/admin/edit_homepage.html
{% extends "catalogue/base.html" %}

{% block content %}

<h3>Complete the form below to alter the text that appears on your group's homepage (<a href="{{cooperative.get_absolute_absolute_url}}">{{cooperative.get_absolute_absolute_url}}</a>).
<form action="" method="post">
{{form.as_p}}
<input type="submit">
</form>

{% endblock%}

catalogue/templates/catalogue/admin/edit_order.html
{% extends "catalogue/base.html" %}

{% block extrahead %}
{{ block.super }}
{{ form.media }}
<script type="text/javascript"><!--
$(document).ready(function() {
    $('input#id_closing_date').datepicker({'dateFormat':'yy-mm-dd'});
    $('input#id_delivery_date').datepicker({'dateFormat':'yy-mm-dd'});
});
//--></script>
{% endblock %}

{% block content %}

<form action="" method="post">
{{form.as_p}}
<input type="submit">
</form>

{% endblock%}

catalogue/templates/catalogue/admin/email_all_members.html
{% extends "catalogue/base.html" %}

{% block content %}

<h3>Complete the form below to send an email to all your members</h3>
<form action="" method="post">
{{form.as_p}}
<input type="submit">
</form>

{% endblock%}

catalogue/templates/catalogue/admin/members.html
{% extends "catalogue/base.html" %}

{% block content %}
<div class="messages">
{% for message in messages %}
<p>{{message}}</p>
{% endfor %}
</div>

<h2>Group Members</h2>

{% if members %}
    <table>
    {% for member in members %}
        <tr>
        <td><p>{{member.name}}</p></td>
        <td><p>{{member.username}}</p></td>
        <td><p>{{member.email}}</p></td>
        <td><p><a href="/coop-admin/members/edit/{{member.id}}/">Edit</a></p></td>
        <td><p><a href="/coop-admin/members/delete/{{member.id}}/">Delete</a></p></td>
        </tr>
    {% endfor %}
    </table>
    <p><a href="/coop-admin/members/new/">Add a new member</a></p>
    <p><a href="/coop-admin/members/email-all/">Send an email to all members</a></p>
{% else %}
    <p>Your group has no members.</p>
{% endif %}

{% endblock%}

catalogue/templates/catalogue/admin/order_collated.html
{% extends 'catalogue/base.html' %}

{% block content %}
<table>
<tr>
<th>Product</th>
<th>Size</th>
<th>Unit price</th>
<th>Units ordered</th>
<th>Surplus units</th>
<th>Units required</th>
<th>Cost</th>
</tr>
{% for row in data %}
<tr{% if row.product.is_splittable %} class="splittable"{% endif %}>
<td><p>{{row.product}}</p></td>
<td><p>{{row.product.size}}</p></td>
<td><p style="text-align:right">{{row.product.gross_price|stringformat:".2f"}}</p></td>
<td><p style="text-align:right">{{row.outgoing_units}}</p></td>
<td><p style="text-align:right">{% if row.surplus_units %}{{row.surplus_units}}{% endif %}</p></td>
<td><p style="text-align:right">{{row.units_required}}</p></td>
<td><p style="text-align:right">{{row.cost|stringformat:".2f"}}</p></td>
</tr>
{% endfor %}
</table>
<p>Grand total: <strong>{{grand_total}}</strong></p>
<p><a href="./?download=True">Download as csv file</a></p>
{% endblock %}

catalogue/templates/catalogue/admin/order_collated_csv.html
"Product","Size","Unit price","Units ordered", "Surplus units", "Units required","Split price","Cost"

{% for row in data %}"{{row.product}}","{{row.product.size}}",{{row.product.gross_price|stringformat:".2f"}},{{row.outgoing_units}},{% if row.surplus_units %}{{row.surplus_units}}{% endif %},{{row.units_required}},{% if row.product.is_splittable %}{{ row.product.get_price }}{% endif %},{{row.cost|stringformat:".2f"}}
{% endfor %}"Grand total","","","","","","{{grand_total|stringformat:".2f"}}"

catalogue/templates/catalogue/admin/order_everyone.html
{% extends 'catalogue/base.html' %}

{% block content %}
<p>Sort by: <a href="./?order_by=product">Product</a> | <a href="./?order_by=person">Person</a></p>
<table>
{% for item in items %}
{% ifchanged item.basket.userprofile %}{% ifequal order_by "person" %}<tr>
<td><p><strong>{{ item.basket.userprofile.name }}</strong></p></td>
<td><p></p></td>
<td><p></p></td>
<td><p style="text-align:right">Total:</p></td>
<td><p>{{ item.basket.total_price|stringformat:".2f" }}</p></td>
</tr>{% endifequal %}{% endifchanged %}
<tr{% if item.product.is_splittable %} class="splittable"{% endif %}>
<td><p>{{item.basket.userprofile.name}}</p></td>
<td><p>{{item.product}}</p></td>
<td><p>{{item.product.get_outgoing_unit_size}}</p></td>
<td><p style="text-align:right">{{item.quantity}}</p></td>
<td><p style="text-align:right">{{item.total_price|stringformat:".2f"}}</p></td>
</tr>
{% endfor %}
</table>
<p><a href="./?order_by={{order_by}}&amp;download=True">Download</a></p>
{% endblock %}

catalogue/templates/catalogue/admin/order_everyone_csv.html
{% for item in items %}{% ifchanged item.basket.userprofile %}{% ifequal order_by "person" %}"{{ item.basket.userprofile.name }}","","","Total:","{{ item.basket.total_price|stringformat:".2f" }}"
{% endifequal %}{% endifchanged %}"{{item.basket.userprofile.name}}","{{item.product}}","{{item.product.get_outgoing_unit_size}}","{{item.quantity}}","{{item.total_price|stringformat:".2f"}}"
{% endfor %}

catalogue/templates/catalogue/admin/upload_catalogue.html
{% extends "catalogue/base.html" %}

{% block extrahead %}
{{ block.super }}
{{ form.media }}
<script type="text/javascript"><!--
$(document).ready(function() {
    $('input#id_start_date').datepicker({'dateFormat':'yy-mm-dd'});
    $('input#id_expiry_date').datepicker({'dateFormat':'yy-mm-dd'});
});
//--></script>
{% endblock %}

{% block content %}
<div class="messages">
{% for message in messages %}
<p>{{message}}</p>
{% endfor %}
</div>

<h2>Catalogue upload</h2>
<p>You want the text version linked <a href="http://www.suma.coop/download-links-3/">here</a>.</p>

<form enctype="multipart/form-data" method="post" action="">
{{ form.as_p }}
<input type="submit" value="Do it" />
</form>

{% endblock%}

catalogue/templates/catalogue/admin/upload_catalogue_done.html
{% extends "catalogue/base.html" %}

{% block content %}
<h2>Catalogue uploaded</h2>
<p>Looks like you successfully uploaded a catalogue.</p>

{% endblock%}